language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
env:
  - NO_INTERACTION=1
matrix:
  include:
    - os: osx
      language: generic
      php: '7.1'
      before_install:
        - brew tap homebrew/php
        - brew update
        - brew install php71
before_script:
  - phpize
  - ./configure --enable-sha3
  - make
script: make test
